#!/bin/bash

VERSION=$(cat VERSION)

for i in bionic focal
do
 for j in avx2 avx sse2 ssse3
 do
  sed -e "s/XX_VERSION_XX/${VERSION}/g;s/MTUNE/$j/g;s/URELEASE/${i}/g" dockerfiles/Dockerfile.lapps-runenv.template > dockerfiles/Dockerfile.lapps-runenv.template.${i}.${j}
 done
done
