#!/bin/bash

useradd -r -U -s /sbin/nologin -d /opt/lapps -M -c "LAppS user" lapps
mkdir -p /opt/lapps/run
chown lapps /opt/lapps/run
chown lapps /opt/lapps/bin/l*
chmod u+s /opt/lapps/bin/lapps*

ldconfig
