#!/bin/bash

useradd -r -U -s /bin/bash -d /opt/lapps/run -M -c "LAppS user" lapps
mkdir -p /opt/lapps/run
chown lapps /opt/lapps/run
chown lapps /opt/lapps/bin/l*
chown -R lapps /opt/lapps/etc
chmod u+s /opt/lapps/bin/lapps*
mkdir /tmp/localhost.certs
cd /tmp/localhost.certs
/opt/lapps/bin/certgen.sh
cp localhost.ca.pem localhost.key localhost.crt /opt/lapps/etc/ssl/certs/
chown -R lapps /opt/lapps/etc/ssl

echo << EOM >> /etc/security/limits.conf
lapps           hard     nofile          102400
lapps           soft     nofile          102400
EOM


ldconfig
