FROM ubuntu:xenial

LABEL "co.new-web" "new WEB() LLP" version 1.0  maintainer "pk@new-web.co" description "LAppS run environment"

RUN apt-get update \
	&& apt-get dist-upgrade -y 

RUN apt-get install -y apt-utils 

RUN apt-get install -y libcrypto++9v5

RUN apt-get install -y luarocks

ENV WORKSPACE /tmp

ADD https://github.com/ITpC/LAppS/blob/master/packages/lapps-0.6.1-amd64.deb ${WORKSPACE}

RUN dpkg -i /tmp/lapps-0.6.1-amd.deb

RUN echo "LAppS-0.6.1 is installed under /opt/lapps prefix. To run LAppS use /opt/lapps/bin/lapps [-d] command. -d is an optional argument do run LAppS as a deamon."

RUN echo "You may add/install libraries you want to use with LAppS from luarocks repository. You may twick this Dockerfile or do these operations within running container."
